### ISSUE TITLE
Provide a way to list products for all locations

### ISSUE THREAD

**Issue by lentschi** [lentschi/expiry_sync_client#3]
Originally brought up by @sap7772000zilla - [see composite issue #1 in the wrapper repository](https://github.com/lentschi/expiry_sync/issues/1):

> Suggestion1: please provide a distinct view that consolidates all expired or STE + individual location that can be accessed at any times.

> Suggestion2: provide an alternative to search in ALL storage as well as local/selected storage only

__My idea to implement this:__ Prepend a pseudo location called "All" to the locations select box (maybe using a different font style). Choosing the new location simply shows product list without the filter on location. The "Add product" buttons and menu entries must disappear as long as no location filter is active.

"Suggestion 2" goes on:

> __Better__, in this view provide a filter that can allow displaying not only the items expired today but also those that will expire in X days/weeks/months.

@sap7772000zilla Actually I don't see the point in _ever_ filtering out those products, that are not expiring soon. (By default, they're sorted by expiration date anyway, so those expired will be on top of the list marked red.)

**Comment by sap7772000zilla** [comment]
Hello.
Your idea will work just fine as long as in the new "All locations" view products are also sorted by expiry date.
Thank you.
